### ISSUE TITLE
Rename three-ar to just ar

### ISSUE THREAD

**Issue by dmarcos** [chenzlabs/aframe-ar#1]
A generic `ar` component would be really cool to explore how a-frame can accomodate these use cases. Right now is tailored to three-ar but in the future we might want to folllow a different path

**Comment by machenmusik** [comment]
My thought there was to have components for the various flavors and then a broader one to pick which to use - similar to hand-controls and laser-controls - just calling that one `ar` seems fitting.  Did you think it better to only have one component?

**Comment by machenmusik** [comment]
There is now an `ar` component that uses `three-ar` component and also sets `vr-mode-ui` enabled to false, thanks for the suggestion!

**Comment by machenmusik** [comment]
(Also renamed the repository to match)
