### ISSUE TITLE
Make the three-ar component set `vr-mode-ui="enabled:false"`

### ISSUE THREAD

**Issue by dmarcos** [chenzlabs/aframe-ar#2]
So users only have to do:
`<a-scene ar>`

**Comment by machenmusik** [comment]
Makes sense - did you want to do quick PR?  If not I should be able to do soon-ish.

**Comment by machenmusik** [comment]
There is now an `ar` component that uses `three-ar` component and also sets `vr-mode-ui` enabled to false, thanks for the suggestion!
