### ISSUE TITLE
reading and writing to arCamera position

### ISSUE THREAD

**Issue by JoshuaCrisp** [chenzlabs/aframe-ar#30]
Is it possible to change or read the arCamera's position and rotation? I am trying to make an object follow the position of an object that has the camera inside of it (using networked-aframe).  This works on the desktop version of my site, but not when I open it on arKit. The camera moves throughout the scene, but its position is not being updated.

**Comment by machenmusik** [comment]
Can you provide a small example and/or be more specific?

There is code that explicitly uses setAttribute so it can be read back
https://github.com/chenzlabs/aframe-ar/blob/master/src/ar-camera.js#L31
But it is possible that recent A-Frame optimizations and/or switch to THREE WebVRManager may have broken it... 

In any case, there is an incantation that should work (and that should probably be exposed more cleanly)
```
var whichar = document.querySelector(’[ar-camera]').components['ar-camera'].checkWhichAR();
var position = whichar.getPosePosition();
var rotation = whichar.getPoseRotation();
```

**Comment by machenmusik** [comment]
Is this still an issue for you?  I believe there were changes in more recent A-Frame versions that broke but then restored this

**Comment by machenmusik** [comment]
@JoshuaCrisp just a quick ping to see whether aframe core fixes made this no longer reproducible using latest master?  If so I will close, if not then if you call provide a simple repro case I can take a look

**Comment by JoshuaCrisp** [comment]
I will take a look and let you know tomorrow! Thanks!

**Comment by machenmusik** [comment]
Thank you for the interest!  If you have additional features you'd like to see, feel free to create issues with your thoughts.

**Comment by JoshuaCrisp** [comment]
I don't know if it was actually broken or if I was just too much of a n00b to understand what I was doing. Either way, it works now (still on frame 8, so not sure about this most recent release.) Sorry to have take so long to respond. I am a student, and was working on a project when i originally posted. As soon as my project was over, I moved on and forgot all about this. That was inconsiderate. I apologize.

**Comment by machenmusik** [comment]
No problem, thanks for letting me know!
