### ISSUE TITLE
aframe-ar on WebARonARKit/Core browser not working.

### ISSUE THREAD

**Issue by edanweis** [chenzlabs/aframe-ar#39]
Platform / Device: Android 8.1.0 - POCOPHONE F1

- aframe Version: `0.8.2`
- aframe-ar `^0.2.1-a`
- three `^0.97.0`
- three-ar-js `^0.1.8`

Glitch examples do not work. The scene loads with sphere and white background but the camera does not respond to any device movement. The console logs `mozilla-ar-xr has loaded`.

Demo:
https://songhe.surge.sh

Code: 
https://github.com/edanweis/aframe-ar-test

How do I get the examples working with WebARonARCore browser? I'm using Vue.js with Webpack to import the modules like so:

```
import { Scene, WebGLRenderer } from 'three';
import { ARUtils, ARPerspectiveCamera, ARView, ARDebug, ARDisplay } from 'three.ar.js';
require('aframe-ar');

	  <a-scene ar>
      <a-box width="0.25" height="0.25" depth="0.25" position="-0.25 0.125 -0.75" rotation="0 45 0" color="#4CC3D9" shadow></a-box>
      <a-sphere position="0 0.3125 -1.25" radius="0.3125" color="#EF2D5E" shadow></a-sphere>
      <a-cylinder position="0.25 0.1875 -0.75" radius="0.125" height="0.375" color="#FFC65D" shadow></a-cylinder>
      <a-plane position="0 0 -1" rotation="-90 0 0" width="1" height="1" color="#7BC8A4" shadow></a-plane>
      <ar-camera></ar-camera>
    </a-scene>

```

**Comment by vincentfretin** [comment]
First, can you check the aframe-ar examples works for you?
I'm not sure arcore-preview.apk works well with Android 8.1. I'm still using Android 7, I didn't update my phone for months for this reason.

You shouldn't import another copy of three. You should use the global THREE (so window.THREE), the version bundled with aframe.

**Comment by edanweis** [comment]
The aframe-ar hello-world example doesn't work for me. The console shows:

![image](https://user-images.githubusercontent.com/2130136/46446303-d66d4880-c7be-11e8-8ab8-fd9d9b3ddc08.png)

And a screenshot:
![image](https://user-images.githubusercontent.com/2130136/46446315-f3a21700-c7be-11e8-8ee9-8342f662ac20.png)


 The examples at [Google](https://developers.google.com/web/updates/2018/06/ar-for-the-web) work, as well as the [immersive web WebXR](https://immersive-web.github.io/webxr-samples/) ones.

I have installed the arcore-preview.apk. I cannot get arcore-preview2.apk to install.  According to the [android-ar-sdk docs](https://github.com/google-ar/arcore-android-sdk/releases):

> Apps built with the original ARCore SDK Developer Preview are only compatible with the original arcore-preview.apk. Apps built with ARCore SDK Developer Preview 2 are only compatible with arcore-preview2.apk.

Which ARCore apk is aframe-ar compatible with?

I have changed the three.js to window.THREE, but still doesn't work.

**Comment by edanweis** [comment]
I enabled the [WebVR flag](https://flags/#enable-webvr) and now the aframe camera responds to device movement, but there is no pass through to camera stream, and I'm not sure how the `ar` attribute is supposed to implement AR capabilities?

**Comment by machenmusik** [comment]
You're saying aframe-ar.glitch.me, aframe-ar-plane.glitch.me, etc. don't work for your configuration?  Or do they now that the enable-webvr flag is set? (sorry the example sites probably do not have origin trial tokens)

**Comment by machenmusik** [comment]
I believe WebARonARCore only works with arcore-preview (dp1, if I recall correctly)

**Comment by edanweis** [comment]
@machenmusik The glitch examples still do not work, even after turning on the WebVR flag. I see a white background, with yellow text: `no ardisplay?` The missing origin token should not matter, since I've enabled the flags manually. 

I am now running ARCore Version 1.5.180910056. I think Chrome Canary prompts to update from the earlier release, which I did.

**Comment by machenmusik** [comment]
The Glitch examples etc. do not yet work in Chrome Canary, as I understand it, because aframe itself has not yet switched over to using webxrmanager, but is still using webvrmanager and so I don't think it is currently possible to use Chrome Canary's WebXR AR mode.  It is possible I missed changes to that effect though

**Comment by vincentfretin** [comment]
I confirm you need to use WebARonARCore which works only with arcore dp1 (arcore-preview.apk), and so only for Samsung S8 and Google Pixel on Adnroid 7, it was the two phones supported at that time.

And indeed aframe-ar doesn't currently work with Chrome Canary.

**Comment by machenmusik** [comment]
Closing given WebARonARCore reliance on DP1 as mentioned above.
Note that latest A-Frame may include WebXR support which would potentially unblock that pathway, but I believe the ar-raycaster would need changes to use WebXR hit test.
