### ISSUE TITLE
Status of this project - AFrame 0.9.0 and WebXR

### ISSUE THREAD

**Issue by urish** [chenzlabs/aframe-ar#40]
a-frame 0.9.0 has [just been released](https://github.com/aframevr/aframe/releases/tag/v0.9.0), and it brings initial support for WebXR. Do you have any plans to update this repo to work with the new standard so it can be used on standard Chrome browser?

Thanks!

**Comment by machenmusik** [comment]
I hope to have a look over the weekend - thanks for the reminder!

**Comment by urish** [comment]
♥

**Comment by machenmusik** [comment]
Unfortunately mobile Chrome seems a bit broken at the moment, see https://github.com/aframevr/aframe/issues/4002 and https://github.com/aframevr/aframe/issues/4087 - if you hear differently from Googlers we know, feel free to ping me :-)

**Comment by shubhamgithub1** [comment]
after running your project i'm getting error as 

> **ReferenceError: AFRAME is not defined**

**Comment by machenmusik** [comment]
(@shubhamgithub1 - this project is not meant to run standalone, it does require A-Frame and potentially some others as well; see more information in the README.)

**Comment by shubhamgithub1** [comment]
@machenmusik  i follow the readme and build and run the project but still i'm getting same error

**Comment by LuiseSteuckart** [comment]
anyone know why my camera does not open with a-frame AR anymore (am using firefox quantum)?
it worked perfectly when i did a first test about a year or so ago, but now that i want to work on it, it does not open :( any ideas?

**Comment by machenmusik** [comment]
(It may finally be time to pick this up again, using the new version of A-Frame that supports WebXR with hit-test, and as Chrome v81 goes from beta to mainstream...)

**Comment by urish** [comment]
Yes please :)

**Comment by machenmusik** [comment]
OK - for folks with Android Chrome Beta et al., 
try these and see if they work for you
(so far, basic functionality of positioning and hit-test raycaster only)
https://aframe-ar.glitch.me
https://aframe-ar-raycaster-logo-test.glitch.me

**Comment by machenmusik** [comment]
Also https://aframe-ar-horses.glitch.me/
(Note the `raycaster-move` component, which is now necessary with newer aframe raycaster changes)

Not working quite yet with Mozilla WebXR Viewer on iOS, may need some changes from that team, TBD.

**Comment by urish** [comment]
The horses demo works pretty well on my phone (Chrome dev). Is the most recent code here?

https://github.com/chenzlabs/aframe-ar/tree/aframe-1.0.x

I want to try it with my [web-ar-experiment](https://github.com/urish/web-ar-experiment) repo.

**Comment by machenmusik** [comment]
yep `https://cdn.jsdelivr.net/gh/chenzlabs/aframe-ar@aframe-1.0.x/dist/aframe-ar.min.js` (unless I had typos)

**Comment by machenmusik** [comment]
good news - on that branch, basic 6DOF and raycaster are working on latest Mozilla WebXR Viewer for iOS now - forgot that raycaster won't work without world sensing, which defaults to false `<a-scene ar="worldSensing:true" ...>`

planes etc. are still a little broken though, looks like syntax has changed a little.

**Comment by machenmusik** [comment]
Ok, on WebXR Viewer, planes are once again working with the aframe-1.0.x branch.
https://aframe-ar-plane.glitch.me
Not sure that WebXR has working planes yet though.

**Comment by machenmusik** [comment]
I'm gonna close this one for now, but feel free to open new issues for WebXR planes; there is already another issue open for image tracking.

**Comment by urish** [comment]
Thanks! I tested it with my old code, and getting an error on Chrome's console:

`DOMException: Failed to execute 'requestHitTestSource' on 'XRSession': Hit test feature is not supported`

tried both with latest Chrome Dev and Canary. Is there a flag or something that I should enable?

Edit: Device is Google Pixel 2, running Android 10

**Comment by klausw** [comment]
@urish, you need to request "hit-test" as a session feature before using it, see example at https://github.com/klausw/aframe/blob/r-domoverlay/docs/components/webxr.md

```html
<a-scene webxr="requiredFeatures: hit-test,local-floor;
                optionalFeatures: dom-overlay,unbounded;
                overlayElement: #overlay;"></a-scene>
```

About planes not working, do you have more detail? You need to enable "WebXR Incubations" in chrome://flags since they aren't enabled by default. 

You don't get normal DOM events in immersive WebXR sessions. If you're on a desktop VR system, "click" events would be generated by mouse clicks on the monitor view, and for consistency you're supposed to use XR `select` events for XR interactions even for smartphone AR. If you're using DOM Overlay, you could get DOM events from the overlay, but that's not really the intended purpose.

@machenmusik , are you on the A-Frame slack?

**Comment by klausw** [comment]
The documentation link should have been https://aframe.io/docs/master/components/webxr.html - the webxr system configuration is available in A-Frame master, but AFAIK not yet in a regular release.

**Comment by machenmusik** [comment]
@klausw thanks - although aframe-ar's ar component is supposed to set `local-floor,hit-test` automatically.  I do like your broader suggestion better though, may do a change for that later.

**Comment by machenmusik** [comment]
@urish if your old code is `<a-scene ar ...>`
right now it needs to change to `<a-scene ar="worldSensing:true" ...>`
although I am reconsidering just defaulting to true as almost everyone will want raycaster and/or planes.  thoughts?

**Comment by urish** [comment]
Seems like despite changing the code, I'm still getting the error (tried now with Canary). This is what my `<a-scene>` looks like in the DOM inspector:

```html
<a-scene ar="worldSensing:true" inspector="" keyboard-shortcuts="" screenshot="" vr-mode-ui="" device-orientation-permission-ui="" webxr-ar="" mozilla-xr-ar="" ar-planes="" ar-anchors="" webxr="requiredFeatures:hit-test,local-floor">
```

**Comment by klausw** [comment]
> @klausw thanks - although aframe-ar's ar component is supposed to set `local-floor,hit-test` automatically. I do like your broader suggestion better though, may do a change for that later.

Thanks! I think it's a bit unfriendly to unconditionally set the system attributes, especially via overwrite and not append - this would cause hard-to-debug conflicts if for example the user also wants to request `dom-overlay`, or if a separate component tries to make feature requests that get undone this way.

**Comment by machenmusik** [comment]
Agree it should not overwrite if already present (which it might naively do right now) - not sure it should append... open to proposals.

**Comment by machenmusik** [comment]
@urish if you give me a URL to try, I can take a look

**Comment by urish** [comment]
Sure, this is the repo and branch with the up-to-date code:
https://github.com/urish/web-ar-experiment/tree/aframe-1.0.x

there are two files
- cesium.html is basically the demo that is built in [this blog post](https://medium.com/@urish/web-powered-augmented-reality-a-hands-on-tutorial-9e6a882e323e)
- index.html is the second demo with the fox and dinosaur
