### ISSUE TITLE
Refactor scene component and allow AR camera enable/disable.

### ISSUE THREAD

**Issue by machenmusik** [chenzlabs/aframe-ar#5]
Issue from discussion on #4 --

> From our discussion, it seems that you would indeed like to reuse the camera -- and you're probably in the vast majority there; I am thinking that maybe it would be better to refactor things slightly, so that the `ar` scene component introduces an `ar-camera` component on the appropriate camera (specified by selector), that can be enabled / disabled to effect your AR toggling.
With that in mind, I'm going to close this PR and open a corresponding issue.

**Comment by machenmusik** [comment]
potential `ar-camera` component here (explicitly added for the moment):
https://glitch.com/edit/#!/charming-twig

@RSpace if you are still using #4, do you think it makes sense to move `enableARView` / `restorePreviousView` to be in `ar-camera` `update` handler?

**Comment by RSpace** [comment]
That could certainly make sense. I've been a bit away from the AR support, but it looks like you've recently updated this component to also support Mozilla's WebXR API?

I was thinking to switch over to their webxr polyfill, but now it looks like I can get the best of both worlds if I continue to use the library? An update to the readme to clarify support would be highly appreciated.

**Comment by machenmusik** [comment]
@RSpace I added mention of the basic WebXR Viewer support to the README (see #16).  More details of why only basic support for now are in #9.  If you're getting back into doing the AR stuff, maybe I can commit the glitch above that creates an `ar-camera` component into master, and you can then tweak #4 to use `ar-camera` handler for the `enabled` flag in `update` ?

**Comment by machenmusik** [comment]
At the moment, it is possible to use enabled and disabled to hide and show camera passthrough; I would actually prefer being able to smoothly fade in and out, but there appears to be an issue with three.ar.js ARView render there.

Do you think it is still necessary to specify which camera by selector, as opposed to just adding `ar-camera` to whichever you like and using `a-scene ar='takeOverCamera:false'` to prevent the default?

**Comment by machenmusik** [comment]
> possible to use enabled and disabled to hide and show camera passthrough

(But not yet implemented in master, to be clear)

**Comment by machenmusik** [comment]
Closing for now via #17 and #20.
