### ISSUE TITLE
Support ios

### ISSUE THREAD

**Issue by felipeardila1010** [chenzlabs/aframe-ar#64]
regards,

Thank you very much for your contribution of augmented reality, a question for support on iOS? and what explorers or what would be necessary to do for its use?

**Comment by machenmusik** [comment]
On iOS, you can use Mozilla's WebXR Viewer 
https://apps.apple.com/us/app/webxr-viewer/id1295998056
although the new 2.0 version appears to have a more basic implementation of WebXR standard at the moment, compared to their proprietary interface in 1.x

(See #65 / #66.)
