### ISSUE TITLE
Aframe-ar produces white background even without a-sky 

### ISSUE THREAD

**Issue by sulaemansantoso** [chenzlabs/aframe-ar#67]
i'm using aframe-ar latest version. 
and the standard example aframe html
found here : https://codepen.io/mozillavr/pen/BjygdO

the tracking works that the object stays in place but the background is still white

![image](https://user-images.githubusercontent.com/32254285/86474166-7711e300-bd6c-11ea-8bcb-22cf7e71f9a4.png)

am i doing something wrong or is there an issue ?

**Comment by machenmusik** [comment]
With the latest version, I believe you need to use a browser app supporting WebXR AR - for Android phones supporting ARCore, that's Chrome for Android; for iOS phones supporting ARKit, that's Mozilla's WebXR Viewer (not Safari) - the new version of WebXR Viewer has a new implementation of AR functionality so more advanced fatures that work with Chrome for Android's implementation may not work yet on the iOS viewer.

**Comment by machenmusik** [comment]
![Screenshot_20200703-123319_Chrome](https://user-images.githubusercontent.com/2080738/86486521-786dec00-bd29-11ea-8598-dd467edfa0c6.jpg)
Until you press the AR button, the background is white since you need AR camera permissions.
